use completion/ag.nu
use completion/atuin.nu
use completion/brew.nu
use completion/cargo.nu
use completion/docker.nu
use completion/gpg.nu
use completion/mdfind.nu
use completion/neovide.nu
use completion/rg.nu
use completion/rsync.nu
use completion/rustup.nu
use completion/ssh.nu
use completion/tmux.nu
use completion/unix.nu
use completion/vimr.nu
