use completion ag *
use completion cargo *
use completion docker *
use completion git *
use completion mdfind *
use completion rg *
use completion rsync *
use completion rustup *
use completion ssh *
use completion tmux *
use completion unix *
use completion vimr *
